name: Terraform Destroy Infrastructure

on:
  # Manually trigger the workflow
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Confirm infrastructure destruction (type YES)'
        required: true

permissions:
  contents: read

env:
  TF_VERSION: 1.7.4
  AWS_REGION: us-east-1

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
        
    # Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Validate destroy confirmation
    - name: Validate Destroy Confirmation
      if: github.event.inputs.confirm_destroy != 'YES'
      run: |
        echo "Destruction not confirmed. Please type 'YES' to destroy infrastructure."
        exit 1

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init
      
    # Destroy Terraform-managed infrastructure
    - name: Terraform Destroy
      run: |
        terraform destroy -auto-approve